name: Pissaddon
version: ${project.version}
main: me.scb.pissaddon.pissaddon.Pissaddon
api-version: 1.16
depend: [ ProjectKorra ]
permissions:
  bending.command.piss:
    default: true
    description: Shows info about PissAddon.
  bending.command.piss.reload:
    default: op
    description: Reload the config of PissAddon.
  Pissaddon.player:
    default: true
    description: Addon Ability Perms
children:
  bending.ability.GoldenShower: true
  bending.ability.PeeDash: true
  bending.ability.PeeDrain: true
  bending.ability.PeeRocket: true
  bending.ability.PissAura: true
  bending.ability.PissSlide: true
  bending.ability.PissSplatter: true
  bending.ability.PissStream: true
  bending.ability.PissSwirl: true
  bending.ability.PissWave: true
  bending.ability.Tinkle: true
  bending.ability.ToiletExplode: true
  bending.ability.UrinalInfection: true
  bending.ability.UTI: true
  bending.ability.WaterSports: true


